<!-- Design JS -->
<script src="<?= App::config("url") ?>vendor/js/Frontend/design3.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design4.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design5.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design6.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design7.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design8.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design9.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design10.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design11.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design12.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design13.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design14.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design15.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design16.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design17.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design18.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design19.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design20.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design21.js"></script>

<!-- Additional JS -->
<script src="<?= App::config("url") ?>vendor/js/scripts.js"></script>
<script src="<?= App::config("url") ?>vendor/js/inputsanitizers.js"></script>

<!-- Additional JS -->
<script src="<?= App::config("url") ?>vendor/js/scripts.js"></script>

