<!-- Design JS -->
<script src="<?= App::config("url") ?>vendor/js/design1.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design2.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design3.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design4.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design5.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design6.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design7.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design8.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design9.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design10.js"></script>

<script src="<?= App::config("url") ?>vendor/js/design11.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design12.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design13.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design14.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design15.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design16.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design17.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design18.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design19.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design20.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design21.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design22.js"></script>

<script src="<?= App::config("url") ?>vendor/js/design23.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design24.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design25.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design26.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design27.js"></script>

<!-- Functionalities JS -->
<script src="<?= App::config("url") ?>vendor/js/scripts.js"></script>

<script src="<?= App::config("url") ?>vendor/js/Functionalities/inputsanitizers.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/calendar.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/stopwatch.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/tablesports.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/searchbar.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/users.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/memberships.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/staff.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/widgets.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/time.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/constants.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Functionalities/statistics.js"></script>

<!-- Bootstrap -->
<script src="<?= App::config("url") ?>vendor/Bootstrap/bootstrap.js"></script>

