<link href="<?= App::config("url") ?>vendor/Bootstrap/Frontend/styles.pure.css" rel="stylesheet">

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,initial-scale=1">

<title>Gymzone - aplikacija za upravljanje i poslovanje teretane</title>
<meta charset="utf-8">
<meta property="og:title" content="Gymzone - aplikacija za upravljanje teretanom">
<meta property="og:image" content="<?= App::config("url") ?>vendor/images/Frontend/aplikacija-za-upravljanje-teretanom.svg">
<meta property="og:description" content="Gymzone - aplikacija za upravljanje teretanom, kompletan nadzor nad članovima i zaposlenicima. Potpuna statistika i uvid u financije u svakom trenutku. bilo gdje.">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Gymzone - aplikacija za upravljanje i poslovanje teretane, kompletan nadzor nad članovima i zaposlenicima. Potpuna statistika i uvid u financije u svakom trenutku. bilo gdje. Isprobajte demo verziju teretane">
<meta name="keywords" content="teretana, upravljanje teretanom, nadzor teretane, članarine, zaposlenici, financije teretane, poslovanje teretane">
<meta name="author" content="https://www.tinako.hr">

<!-- Favicon -->
<link rel="shortcut icon" type="image/png" href="<?= App::config("url") ?>vendor/favicon.png"/>