<!-- Bootstrap 5 -->
<link href="<?= App::config("url") ?>vendor/Bootstrap/bootstrap.css" rel="stylesheet">

<!-- Font awesome -->
<link href="<?= App::config("url") ?>vendor/FontAwesome/css/all.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/FontAwesome/js/all.js" rel="stylesheet">

<!-- Design CSS -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

<link href="<?= App::config("url") ?>vendor/css/Frontend/design1.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/Frontend/design2.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/Frontend/design3.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/Frontend/design4.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/Frontend/design5.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/Frontend/design6.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/Frontend/design7.css" rel="stylesheet">

<!-- Responsive -->
<link href="<?= App::config("url") ?>vendor/css/Frontend/1_responsive_max_280.css" rel="stylesheet">



<script src="<?= App::config("url") ?>vendor/js/Frontend/design1.js"></script>
<script src="<?= App::config("url") ?>vendor/js/Frontend/design2.js"></script>

<!-- custom CSS -->
<link href="<?= App::config("url") ?>vendor/css/style.css" rel="stylesheet">

<!-- Favicon -->
<link rel="shortcut icon" type="image/png" href="<?= App::config("url") ?>vendor/favicon.png"/>