<!DOCTYPE html>
<html lang="hr">
<head>
    <title>Gymzone</title>
    <meta charset="utf-8">
    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="tinako.hr">
    <?php include "head_css.phtml"?>
</head>
<body>

<!--================Header Menu Area =================-->
<header class="main_menu_area">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="<?= App::config("url") ?>vendor/images/Frontend/logo.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span></span>
            <span></span>
            <span></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="<?= App::config("url") ?>">Naslovna strana</a></li>
                <li class="nav-item"><a class="nav-link" href="#kontakt">Kontakt</a></li>
                <li class="nav-item active dropdown submenu">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Prijava u sustav
                    </a>
                    <ul class="dropdown-menu text-center" aria-labelledby="navbarDropdown" style="margin-top: -20px; background-color: white">
                        <form action="<?php echo App::config("url") ?>login/Login" method="post">
                            <label class="" for="">Korisničko ime</label><br>
                            <input class="" name="Staff_Username" type="text" placeholder="Upiši korisničko ime" oninvalid="this.setCustomValidity('Korisničko ime je obavezno')" oninput="setCustomValidity('')" required><br><br>
                            <label class="" for="">Lozinka</label><br>
                            <input class="" name="Staff_Password" type="password" placeholder="Upiši lozinku" oninvalid="this.setCustomValidity('Lozinka je obavezna')" oninput="setCustomValidity('')" required><br><br>

                            <input type="submit" value="Prijava">

                        </form>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!--================End Header Menu Area =================-->


<!--================Slider Area =================-->
<?php if (isset($message)):?>
    <?=$message?>
<?php endif;?>
<section class="main_slider_area" style="background: url('<?= App::config("url") ?>vendor/images/Frontend/slider-bg-1.png') no-repeat scroll center center; padding-top: 3cm">
    <div class="container">
        <div class="row" style="min-height: 500px">
            <div class="col-lg-7 col-md-12 text-center" style="padding-top: 300px">
                <h2>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h2>
                <br>
                <h5 style="font-weight: 200; text-transform: uppercase">Brand Identity</h5>
            </div>
            <div class="col-lg-5 d-none d-lg-block d-xl-block">
                <img src="<?= App::config("url") ?>vendor/images/Frontend/slider-m-1.png" alt="">
            </div>
        </div>
    </div>

</section>
<!--================End Slider Area =================-->

<!--================Feature Area =================-->
<section class="feature_area">
    <div class="container">
        <div class="c_title">
            <img src="<?= App::config("url") ?>vendor/images/Frontend/title-icon.png" alt="">
            <h6>Discover the features</h6>
            <h2>We are young but bold</h2>
        </div>
        <div class="row feature_inner">
            <div class="col-lg-4 col-sm-6">
                <div class="feature_item">
                    <div class="f_icon">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/f-icon-1.png" alt="">
                    </div>
                    <h4>Brand Identity</h4>
                    <p>Etiam nec odio vestibulum est mattis effic iturut magna. Pellentesque sit am et tellus blandit. Etiam nec odio vestibul. </p>
                    <a class="more_btn" href="#">Read More</a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="feature_item">
                    <div class="f_icon">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/f-icon-2.png" alt="">
                    </div>
                    <h4>Online Marketing</h4>
                    <p>Etiam nec odio vestibulum est mattis effic iturut magna. Pellentesque sit am et tellus blandit. Etiam nec odio vestibul. </p>
                    <a class="more_btn" href="#">Read More</a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="feature_item">
                    <div class="f_icon">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/f-icon-3.png" alt="">
                    </div>
                    <h4>Social Media</h4>
                    <p>Etiam nec odio vestibulum est mattis effic iturut magna. Pellentesque sit am et tellus blandit. Etiam nec odio vestibul. </p>
                    <a class="more_btn" href="#">Read More</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Feature Area =================-->

<!--================The best slider Area =================-->
<section class="best_3d_area">
    <div class="left_3d" style="background: url('<?= App::config("url") ?>vendor/images/Frontend/3d-slider-shap.png') no-repeat scroll center center;">
        <div class="shap_slider_inner">
            <div class="item">
                <h4>“They are the best”</h4>
                <p>Etiam nec odio vestibulum est mattis effic iturut magna. Pellentesque sit am et tellus blandit. Etiam nec odio vestibul. Etiam nec odio vestibulum est mattis effic iturut magna. Pellentesque sit am et tellus.</p>
                <div class="media">
                    <img src="<?= App::config("url") ?>vendor/images/Frontend/people-5.jpg" alt="">
                    <div class="media-body">
                        <h5>Chriss Turner</h5>
                        <h6>CEO Enterprise</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="right_text">
        <div class="right_text_inner">
            <div class="text_3d">
                <div class="l_title">
                    <img src="<?= App::config("url") ?>vendor/images/Frontend/title-icon.png" alt="">
                    <h6>Discover the features</h6>
                    <h2>We don’t hide, we stand tall in front of chalenge</h2>
                </div>
                <p>Etiam nec odio vestibulum est mattis effic iturut magna. Pellentesque sit am et tellus blandit. Etiam nec odio vestibul.Cras ex mauris, ornare eget pretium sit amet, dignissim et turpis. Nunc nec maximus dui, vel suscipit dolor. Donec elementum velit a orci facilisis rutrum. Nam convallis vel erat id dictum. Sed ut risus in orci convallis viverra a eget nisi. Aenean pellentesque elit vitae eros dignissim ultrices. </p>
            </div>
            <div class="shap_mobile">
                <img src="<?= App::config("url") ?>vendor/images/Frontend/iphone4.png" alt="">
            </div>
        </div>
    </div>
</section>
<!--================End The best slider Area =================-->

<!--================Team People Area =================-->
<section class="team_people_area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="team_people_text">
                    <div class="l_title">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/title-icon.png" alt="">
                        <h6>Discover the features</h6>
                        <h2>We build a strong team of great people</h2>
                    </div>
                    <p>Cras ex mauris, ornare eget pretium sit amet, dignissim et turpis. Nunc nec maximus dui, vel suscipit dolor. Donec elementum velit a orci facilisis rutrum. Nam convallis vel erat id dictum. Sed ut risus in orci convallis viverra.</p>
                    <ul>
                        <li><a href="#">Nunc nec maximus dui, </a></li>
                        <li><a href="#">Aenean pellentesque elit vitae</a></li>
                        <li><a href="#">Aenean pellentesque elit vitae</a></li>
                        <li><a href="#">Ex mauris, ornare eget pretium </a></li>
                        <li><a href="#">Cras ex mauris, ornare eget preti</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="team_img_inner">
                    <div class="row">
                        <div class="col-lg-6 col-6">
                            <div class="team_img_item">
                                <img src="<?= App::config("url") ?>vendor/images/Frontend/people-1.jpg" alt="">
                            </div>
                        </div>
                        <div class="col-lg-6 col-6">
                            <div class="team_img_item">
                                <img src="<?= App::config("url") ?>vendor/images/Frontend/people-2.jpg" alt="">
                            </div>
                        </div>
                        <div class="col-lg-6 col-6">
                            <div class="team_img_item">
                                <img src="<?= App::config("url") ?>vendor/images/Frontend/people-3.jpg" alt="">
                            </div>
                        </div>
                        <div class="col-lg-6 col-6">
                            <div class="team_img_item">
                                <img src="<?= App::config("url") ?>vendor/images/Frontend/people-4.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Team People Area =================-->

<!--================Get in Touch Area =================-->
<section class="get_in_touch_area" id="kontakt">
    <div class="container">
        <div class="row get_touch_inner">
            <div class="col-lg-6">
                <form class="contact_us_form row" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                    <div class="form-group col-lg-6">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                    </div>
                    <div class="form-group col-lg-6">
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject*">
                    </div>
                    <div class="form-group col-lg-12">
                        <textarea class="form-control" name="message" id="message" rows="1" placeholder="Message"></textarea>
                    </div>
                    <div class="form-group col-lg-12">
                        <button type="submit" value="submit" class="btn submit_btn form-control">Send</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6">
                <div class="touch_details">
                    <div class="l_title">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/title-icon.png" alt="">
                        <h6>Say hello</h6>
                        <h2>Get in touch, send us an e-mail or call us</h2>
                    </div>
                    <p>Cras ex mauris, ornare eget pretium sit amet, dignissim et turpis. Nunc nec maximus dui, vel suscipit dolor. Donec elementum velit a orci facilisis rutrum.</p>
                    <a href="#"><h5>Call us now</h5></a>
                    <a href="#"><h4>+452373 95593 232</h4></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Get in Touch Area =================-->

<!--================Map Area =================-->
<section class="world_map_area p_100">
    <div class="container">
        <div class="world_map_inner">
            <img class="img-fluid" src="<?= App::config("url") ?>vendor/images/Frontend/world-map.png" alt="">
            <div class="bd-callout">
                <h3>Gibraltar Office</h3>
                <p>Casemates Square, no253 <br /> United kingdom</p>
                <h4><a href="#">+453678 9283 559</a> <a href="#">contact@template.com</a></h4>
            </div>
        </div>
    </div>
</section>
<!--================End Map Area =================-->

<!--================Footer Area =================-->
<footer class="footr_area">
    <div class="footer_widget_area" style="background: url('<?= App::config("url") ?>vendor/images/Frontend/footer-bg.jpg') no-repeat scroll center center;">
        <div class="container">
            <div class="row footer_widget_inner">
                <div class="col-lg-4 col-sm-6">
                    <aside class="f_widget f_about_widget">
                        <img src="img/footer-logo.png" alt="">
                        <p>Cras ex mauris, ornare eget pretium sit amet, dignissim et turpis. Nunc nec maximus dui, vel suscipit dolor. Donec elementum velit a orci facilisis rutrum.</p>
                    </aside>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <aside class="f_widget f_insta_widget">
                        <div class="f_title">
                            <h3>Instagram</h3>
                        </div>
                        <ul>
                            <li><a href="#"><img src="img/instagram/ins-1.jpg" alt=""></a></li>
                            <li><a href="#"><img src="img/instagram/ins-2.jpg" alt=""></a></li>
                            <li><a href="#"><img src="img/instagram/ins-3.jpg" alt=""></a></li>
                            <li><a href="#"><img src="img/instagram/ins-4.jpg" alt=""></a></li>
                            <li><a href="#"><img src="img/instagram/ins-5.jpg" alt=""></a></li>
                            <li><a href="#"><img src="img/instagram/ins-6.jpg" alt=""></a></li>
                            <li><a href="#"><img src="img/instagram/ins-7.jpg" alt=""></a></li>
                            <li><a href="#"><img src="img/instagram/ins-8.jpg" alt=""></a></li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <aside class="f_widget f_subs_widget">
                        <div class="f_title">
                            <h3>Subscribe to newsletter</h3>
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Your e-mail address here" aria-label="Your e-mail address here">
                            <span class="input-group-btn">
                                        <button class="btn btn-secondary submit_btn" type="button">Subscribe</button>
                                    </span>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_copyright">
        <div class="container">
            <div class="float-sm-left">
                <h5><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></h5>
            </div>
            <div class="float-sm-right">
                <ul>
                    <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>


</body>
</html>