<!doctype html>
<html lang="hr">
<head>
    <title>Gymzone</title>
    <meta charset="utf-8">
    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="tinako.hr">
    <?php include "head_css.phtml"?>
</head>
<body class="hold-transition sidebar-mini layout-fixed pace-primary">

<div class="wrapper">
    <?php include "widgets.phtml";?>
    <?php include "navbar.phtml"?>
    <?php include "sidebar.phtml";?>
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item linkanimation">Kontrolna ploča</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3><?=number_format($activeUsersCount, 0, '', '.')?></h3>
                                <p>Aktivnih korisnika</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-users"></i>
                            </div>
                            <!--
                            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                             -->
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3><?=$monthlyUserProportion?><sup style="font-size: 20px">%</sup></h3>
                                <p>Korisnika u odnosu na prošli mjesec</p>
                            </div>
                            <div class="icon">
                                <i class="fad fa-chart-bar"></i>
                            </div>
                            <!--
                            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                             -->
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3 style="color: #FFF"><?=number_format($newMonthlyUsers, 0, '', '.') ?></h3>

                                <p style="color: #FFF">Novih korisnika ovaj mjesec</p>
                            </div>
                            <div class="icon">
                                <i class="fad fa-user-plus"></i>
                            </div>
                            <!--
                            <a href="#" class="small-box-footer"><span style="color: #FFF;">More info</span> <i class="fas fa-arrow-circle-right" style="color: #FFF;"></i></a>
                             -->
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-danger">
                            <div class="inner">
                                <h3><?=number_format($monthlyIncome, 2, ',', '.') ?> KN</h3>
                                <p>Mjesečni prihodi</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-chart-line"></i>
                            </div>
                            <!--
                            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                             -->
                        </div>
                    </div>
                </div>
                <div>
                    <div class="row">
                        <section class="col-xl-8 col-lg-12 d-none d-lg-block d-xl-block connectedSortable">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Pregled korisnika</h3>
                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="card-tools">

                                </div>
                                <div class="card-body div_mainsearbox">

                                    <input type="text" name="search" id="search" placeholder="Pretraživanje korisnika po broju kartice, imenu ili prezimenu" class="form-control text-center mainsearchbox" onkeyup="searchfunction()" />
                                    <div class="card-body" id="dt1" style="max-width: available">
                                        <table class="table" id="" width=100%" cellspacing="0">
                                            <thead>
                                            <tr>
                                                <th style="width: auto">Šifra korisnika</th>
                                                <th style="width: auto">Ime i prezime</th>
                                                <th style="width: auto">Vrsta članarine</th>
                                                <th style="width: auto">Aktivan</th>
                                                <th style="width: auto">Datum početka</th>
                                                <th style="width: auto">Datum isteka</th>
                                                <th></th>
                                            </tr>
                                            </thead>

                                            <tbody id="dataTableBody"></tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <section class="col-xl-4 d-lg-none d-xl-block connectedSortable">
                            <div class="card ">
                                <div class="card-header">
                                    <h3 class="card-title">Statistika novih korisnika</h3>
                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="chart">
                                        <canvas id="areaChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                                    </div>
                                </div>
                            </div>
                            <div id="calendar"></div>
                            <div class="card bg-gradient-success">
                                <div class="card-body pt-0 text-center">
                                    <h1 id="clockDisplay" style="padding-top: 20px" onload="showTime()"></h1>
                                    <h4><?=date('d.m.Y')?></h4>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
        </section>
    </div>
    <?php include "footer.phtml";?>
</div>
</body>
</html>