<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?&amp;display=swap" rel="stylesheet" referrerpolicy="no-referrer"
          media="print" onload="if(!window._isAppPrerendering)this.removeAttribute('media');">
    <link href="https://fonts.googleapis.com/css2?&amp;display=swap" rel="preload" referrerpolicy="no-referrer"
          as="style">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&amp;display=swap" rel="stylesheet"
          referrerpolicy="no-referrer" media="print"
          onload="if(!window._isAppPrerendering)this.removeAttribute('media');">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&amp;display=swap" rel="preload"
          referrerpolicy="no-referrer" as="style">
    <link href="https://fonts.gstatic.com/" rel="preconnect" referrerpolicy="no-referrer" >
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="<?= App::config("url") ?>vendor/css/Frontend/design1.css" rel="stylesheet">
    <title>Gymzone</title>
    <link data-vue-meta="1" rel="icon" href="data:;base64,iVBORw0KGgo=">
    <meta data-vue-meta="1" data-vmid="description" name="description" content="">
    <meta data-vue-meta="1" data-vmid="og:title" property="og:title" content="Home">
    <meta data-vue-meta="1" data-vmid="og:description" property="og:description" content="">
    <meta data-vue-meta="1" data-vmid="og:type" property="og:type" content="application">
    <meta data-vue-meta="1" data-vmid="og:url" property="og:url" content="">
    <meta data-vue-meta="1" data-vmid="og:site_name" property="og:site_name" content="">
</head>
<body>

<div class="container-fluid" style="background-color: black; padding-top: 20px">
    <div class="row">
        <div class="col-12 text-right" style="text-align: right">
            <span>
                <a class="navbarNav" href="<?= App::democonfig("url") ?>" target="_blank">Demo</a>

            </span>
                <a class="navbarNav navbarNavDesno"  data-bs-toggle="modal" data-bs-target="#modalLoginForm">Prijava</a>
        </div>
    </div>
</div>

<div id="app" data-server-rendered="true">
    <main>
        <section data-v-a3fd9bac="" class="block block--grid" style="--content-width:1600px; --grid-width:1224px; --column-count:12; --content-padding:16px; --rows:16; --width:1224px; --row-gap:16px; --row-size:48px; --column-gap:24px; --block-padding-top:0px; --block-padding:0px 0px 0px 0px; --block-padding-right:0px; --block-padding-bottom:0px; --block-padding-left:0px; --m-block-padding:36px 0px 0px 0px; --oldContentWidth:1600px;">
            <div data-v-a3fd9bac="" class="block-background" style="--background-color:transparent; --background-overlay-opacity:0;">
                <img alt="" src="<?= App::config("url") ?>vendor/images/Frontend/pozadina2.svg" srcset="" width="100vw" sizes="100vw" loading="eager" class="block-background__image">
            </div>

            <div data-v-1f24cc0f="" data-v-a3fd9bac="" class="block-grid" id="ztIhP7">
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridtextbox:zpqu46"
                     class="block-grid-item use-m-margin grid__item "
                     style="--text:left; --align:flex-start; --justify:flex-start; --m-width:92.6121%; --position:4/3/10/9; --m-align-self:center; --m-element-margin:0 0 12px 0; --element-z-index:3;">
                    <div data-v-189c24f4="" class="text-box block-grid-item__component mobgrid1" id="zpQU46"
                         style="height: 500px; line-height: 130px"><h1><span
                                    style="color: var(--colors-light); ">Kompletan nadzor vaše </span><span
                                    style="color: var(--colors-secondary); ">teretane</span>
                        </h1></div>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridtextbox:zx2npe" class="block-grid-item use-m-margin grid__item mobgrid2" style="--text:left; --align:flex-start; --justify:flex-start; --m-width:90.2375%; --position:10/3/11/7; --m-align-self:center; --m-element-margin:0 0 33px 0; --element-z-index:6; padding-top: 100px;">
                    <div data-v-189c24f4="" class="text-box block-grid-item__component mobgrid1" id="zx2Npe"><p class="body" style=""><span
                                    style="color: var(--colors-light);">Upravljajte svim dijelovima vašeg poslovanja s jednog mjesta.</span>
                        </p></div>
                </div>

                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridimage:zerq3u" class="block-grid-item use-m-margin grid__item" style="--align:center; --justify:center; --m-width:86.5435%; --position:1/8/16/17; --object-fit:contain; --m-align-self:center; --m-element-margin:0 0 16px 0; --element-z-index:1;">
                    <div data-v-00c3b48d="" data-v-189c24f4="" title="" class="block-grid-item__component image">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/homepage.png" alt="" style="width: 100%">
                    </div>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridimage:zmqwfp" class="block-grid-item use-m-margin grid__item" style="--align:center; --justify:center; --position:11/1/17/17; --object-fit:cover; --m-element-margin:0 0 16px 0; --element-z-index:2;">
                    <div data-v-00c3b48d="" data-v-189c24f4="" title="" class="block-grid-item__component image">
                        <img data-v-00c3b48d="" data-qa="builder-gridelement-image" alt="" src="<?= App::config("url") ?>vendor/images/Frontend/wave1-YNqLX3MXWaFq2gXd.svg" sizes="(min-width: 920px) 1920px, calc(100vw - 0px)" height="368" width="1920" loading="lazy" class="image__image image__image--reset-m-position">
                    </div>
                </div>
            </div>
        </section>
        <section data-v-a3fd9bac="" class="block block--grid" style="--content-width:1600px; --grid-width:1224px; --column-count:12; --content-padding:16px; --rows:9; --width:1224px; --row-gap:16px; --row-size:48px; --column-gap:24px; --block-padding-top:16px; --block-padding:16px 0px 16px 0px; --block-padding-right:0px; --block-padding-bottom:16px; --block-padding-left:0px; --m-block-padding:60px 16px 72px 16px; --oldContentWidth:1600px;">
            <div data-v-1f24cc0f="" data-v-a3fd9bac="" class="block-grid" id="zORlYa">
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridtextbox:zcjcem"
                     class="block-grid-item use-m-margin grid__item"
                     style="--text:left; --align:flex-start; --justify:flex-start; --m-width:76.9452%; --position:3/10/6/15; --m-element-margin:0 0 24px 0; --element-z-index:2;">
                    <div data-v-189c24f4="" class="text-box block-grid-item__component mobgrid3" id="zcJcEm"
                    ><h2 style="height: 100px"><span style="color: rgb(0, 0, 0); ">Svi članovi na </span><span style="color: var(--colors-primary);">jednom mjestu</span>
                        </h2>
                    </div>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridtextbox:zd7ajl"
                     class="block-grid-item use-m-margin grid__item"
                     style="--text:left; --align:flex-start; --justify:flex-start; --m-width:90.2017%; --position:6/10/8/15; --m-element-margin:0 0 60px 0; --element-z-index:3;">
                    <div data-v-189c24f4="" class="text-box block-grid-item__component mobgrid4" id="zD7AJL"
                    ><p class="body" style=""><span
                                    style="color: rgb(0, 0, 0); ">Pregled nad članovima, probnim treninzima, promjene i zamrzavanje članarina, upravljanje zaposlenicima i još mnogo toga. Bezbroj mogućnosti za najbolje teretane.</span>
                        </p>
                    </div>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridimage:zh7f5w" class="block-grid-item use-m-margin grid__item" style="--align:center; --justify:center; --position:1/3/9/9; --object-fit:cover; --border-radius:5%; --m-element-margin:0 0 16px 0; --element-z-index:1;">
                    <div data-v-00c3b48d="" data-v-189c24f4="" title="" class="block-grid-item__component image">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/macbook.png" alt="" style="border-radius: 5%; width: 100%">
                    </div>
                </div>
            </div>
        </section>
        <section data-v-a3fd9bac="" class="block block--grid" style="--content-width:1600px; --grid-width:1224px; --column-count:12; --content-padding:16px; --rows:10; --width:1224px; --row-gap:16px; --row-size:48px; --column-gap:24px; --block-padding-top:16px; --block-padding:16px 0px 16px 0px; --block-padding-right:0px; --block-padding-bottom:16px; --block-padding-left:0px; --m-block-padding:60px 16px 60px 16px; --oldContentWidth:1600px;">
            <div data-v-1f24cc0f="" data-v-a3fd9bac="" class="block-grid" id="zS3xAE">
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridtextbox:za1pq1" class="block-grid-item use-m-margin grid__item" style="--text:left; --align:flex-start; --justify:flex-start; --m-width:82.7089%; --position:4/3/7/8; --m-element-margin:0 0 24px 0; --element-z-index:2;">
                    <div data-v-189c24f4="" class="text-box block-grid-item__component mobgrid5" id="za1PQ1"
                    ><h2 style="height: 250px"><span style="color: rgb(0, 0, 0);">Detaljna statistika </span><span
                                    style="color: var(--colors-primary);">nadohvat ruke</span>
                        </h2></div>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridtextbox:zqdupd"
                     class="block-grid-item use-m-margin grid__item"
                     style="--text:left; --align:flex-start; --justify:flex-start; --m-width:88.4726%; --position:7/3/9/8; --m-element-margin:0 0 60px 0; --element-z-index:3;">
                    <div data-v-189c24f4="" class="text-box block-grid-item__component mobgrid6" id="zQDUPd"
                    ><p class="body" style=""><span
                                    style="color: rgb(0, 0, 0);">Točni i detaljni podaci dostupni u svakom trenutku - za bilo koje razdoblje. Iskoristite potpunu snagu aplikacije i imajte uvid u statistiku poslovanja kao nikad do sad.</span>
                        </p>
                    </div>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridimage:zg47jk" class="block-grid-item use-m-margin grid__item" style="--align:center; --justify:center; --position:2/9/10/15; --object-fit:cover; --border-radius:5%; --m-element-margin:0 0 16px 0; --element-z-index:1;">
                    <div data-v-00c3b48d="" data-v-189c24f4="" title="" class="block-grid-item__component image">
                        <img src="<?= App::config("url") ?>vendor/images/Frontend/stats.png" height="496" width="600" alt="" style="border-radius: 5%; width: 100%; height: auto">
                    </div>
                </div>
            </div>
        </section>

        <section data-v-a3fd9bac="" class="block block--grid"
                 style="--content-width:1600px; --grid-width:1224px; --column-count:12; --content-padding:16px; --rows:4; --width:1224px; --row-gap:16px; --row-size:48px; --column-gap:24px; --block-padding-top:0px; --block-padding:0px 0px 0px 0px; --block-padding-right:0px; --block-padding-bottom:0px; --block-padding-left:0px; --m-block-padding:0px 0px 40px 0px; --oldContentWidth:1600px; margin-top: -50px">
            <div data-v-a3fd9bac="" class="block-background"
                 style="--background-color:var(--colors-dark); --background-overlay-opacity:0;"><!----><!----></div>
            <div data-v-1f24cc0f="" data-v-a3fd9bac="" class="block-grid"  id="zqSGeg">
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridimage:zpxu8a"
                     class="block-grid-item use-m-margin grid__item"
                     style="--align:center; --justify:center; --position:1/1/5/17; --object-fit:cover; --m-element-margin:0 0 16px 0; --element-z-index:1;">
                    <div data-v-00c3b48d="" data-v-189c24f4="" title="" class="block-grid-item__component image"><img
                                data-v-00c3b48d="" data-qa="builder-gridelement-image" alt=""
                                src="<?= App::config("url") ?>vendor/images/Frontend/wave2-mjEDL1VgkGsr5nwz.png"
                                srcset=""
                                sizes="(min-width: 920px) 1920px, calc(100vw - 0px)" width="1920"
                                loading="lazy" class="image__image image__image--reset-m-position"></div>
                </div>
            </div>
        </section>


        <section data-v-a3fd9bac="" class="block block--grid"
                 style="--content-width:1600px; --grid-width:1224px; --column-count:12; --content-padding:16px; --rows:14; --width:1224px; --row-gap:16px; --row-size:48px; --column-gap:24px; --block-padding-top:0px; --block-padding:0px 0px 0px 0px; --block-padding-right:0px; --block-padding-bottom:0px; --block-padding-left:0px; --m-block-padding:88px 0px 0px 0px; --oldContentWidth:1600px;">
            <div data-v-a3fd9bac="" class="block-background"
                 style="--background-color:transparent; --background-overlay-opacity:0;"><img alt="" src="<?= App::config("url") ?>vendor/images/Frontend/pozadina2.svg" srcset="" width="100vw" sizes="100vw" loading="lazy" class="block-background__image">
            </div>
            <div data-v-1f24cc0f="" data-v-a3fd9bac="" class="block-grid" id="download" style="margin-top: -120px">
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridtextbox:zpocr1"
                     class="block-grid-item use-m-margin grid__item"
                     style="--text:left; --align:flex-start; --justify:flex-start; --m-width:90.7652%; --position:4/10/9/15; --m-align-self:center; --m-element-margin:0 0 40px 0; --element-z-index:2;">
                    <div data-v-189c24f4="" class="text-box block-grid-item__component" id="zpoCr1"
                    ><h2 style="margin-bottom: 0; height: 150px" class="mobgrid7"><span
                                    style="color: var(--colors-light);"><strong>Cloud aplikacija</strong></span>
                        </h2>
                        <p class="body" style=""><span
                                    style="color: var(--colors-light);">Kvalitetni internet serveri osiguravaju neometan pristup najbitnijim podacima vaše teretane s bilo kojeg uređaja, bez obzira gdje se nalazili. </span>
                        </p></div>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridbutton:zpxwoi" class="block-grid-item use-m-margin grid__item mobgrid8" style="--align:flex-start; --justify:center; --m-width:90.2375%; --position:9/10/11/12; --m-align-self:center; --m-element-margin:0 0 16px 0; --element-z-index:4;">
                    <a data-v-2f409ee5="" data-v-189c24f4="" data-bs-toggle="modal" data-bs-target="#modalContactForm" class="grid-button block-grid-item__component grid-button--primary" id="zpxWOi">
                        Kontakt
                    </a>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridbutton:znfjdb" class="block-grid-item use-m-margin grid__item mobgrid8" style="--align:flex-start; --justify:center; --m-width:89.7098%; --position:9/12/11/14; --m-align-self:center; --m-element-margin:0 0 16px 0; --element-z-index:5;">
                    <a data-v-2f409ee5="" data-v-189c24f4="" href="<?= App::democonfig("url") ?>" target="_blank"
                       class="grid-button block-grid-item__component grid-button--secondary" id="zNfJDB">Demo
                    </a>
                </div>
                <div data-v-189c24f4="" data-v-1f24cc0f="" data-qa="gridimage:z169jn" class="block-grid-item use-m-margin grid__item" style="--align:center; --justify:center; --m-width:90.2017%; --position:1/3/14/9; --object-fit:contain; --m-align-self:center; --border-radius:5%; --m-element-margin:0 0 16px 0; --element-z-index:1;">
                    <div data-v-00c3b48d="" data-v-189c24f4="" title="" class="block-grid-item__component image">
                        <img data-v-00c3b48d="" data-qa="builder-gridelement-image" alt="" src="<?= App::config("url") ?>vendor/images/Frontend/mob.png" sizes="(min-width: 920px) 600px, calc(100vw - 0px)" loading="lazy" class="image__image image__image--reset-m-position" style="width: 100%">
                    </div>
                </div>

            </div>
        </section>
    </main>

    <!-- Modal start -->
    <!-- login modal -->
    <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog " role="document" style="max-width: 400px; margin-top: 2cm">
            <div class="modal-content modallogin">
                <div class="modal-body">
                    <div class="form-title text-center">
                        <p class="navbarNav" style="color: black; margin-top: 20px">prijava</p>
                    </div>
                    <div class="d-flex flex-column text-center" style="margin-top: 30px; padding-left: 30px; padding-right: 30px">
                        <form id="loginform">
                            <div class="form-group">
                                <input type="text" class="form-control" name="Staff_Username" id="Staff_Username" placeholder="Korisničko ime" oninvalid="this.setCustomValidity('Molimo unesite ispravno korisničko ime.')" oninput="setCustomValidity('')" required>
                            </div>
                            <div class="form-group" style="margin-top: 10px">
                                <input type="password" class="form-control" name="Staff_Password" id="Staff_Password" placeholder="Lozinka" oninvalid="this.setCustomValidity('Molimo unesite ispravnu lozinku.')" oninput="setCustomValidity('')" required>
                            </div>
                            <div><p class="invalidDataNotice" id="invalidDataNotice">Korisničko ime i/ili lozinka nisu ispravni</p></div>
                            <input class="prijavaGumb" type="submit" value="Prijava" form="loginform" style="margin-top: 20px">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- contact modal -->
    <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog " role="document" style="max-width: 500px; margin-top: 2cm">
            <div class="modal-content modallogin">
                <div class="modal-body">
                    <div class="form-title text-center">
                        <p class="navbarNav" style="color: black; margin-top: 20px">Zatražite kontakt</p>
                    </div>
                    <div class="d-flex flex-column text-center" style="margin-top: 30px; padding-left: 30px; padding-right: 30px">
                        <form id="contactform">
                            <div><p class="contactData" id="contactData">Zainteresirani ste za aplikaciju? Unesite Vaše podatke i kontaktirati ćemo vas u najkraćem roku.</p></div>

                            <div class="form-group">
                                <input type="email" class="form-control" name="Contact_Email" id="Contact_Email" placeholder="Vaša e-mail adresa" oninvalid="this.setCustomValidity('Molimo unesite ispravnu e-mail adresu.')" oninput="setCustomValidity('')" required>
                            </div>
                            <div class="form-group" style="margin-top: 10px">
                                <textarea rows="3" style="width: 100%" placeholder="Vaša poruka" minlength="3" class="form-control" name="Contact_Message" oninvalid="this.setCustomValidity('Molimo unesite ispravnu poruku.')" oninput="setCustomValidity('')" required></textarea>
                            </div>
                            <div><p class="invalidDataNotice" id="invalidDataNotice">Zahvaljujemo na kontaktu. Odgovoriti ćemo u najkraćem roku.</p></div>
                            <div><p class="invalidDataNotice" id="invalidDataNotice2">Molimo pokušajte ponovo.</p></div>

                            <input class="prijavaGumb" type="submit" value="Slanje poruke" form="contactform" style="margin-top: 20px">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal ends -->
    <?php require "scripts.phtml"?>
</body>
</html>