<!-- Bootstrap 5 -->
<link href="<?= App::config("url") ?>vendor/Bootstrap/bootstrap.css" rel="stylesheet">

<!-- Font awesome -->
<link href="<?= App::config("url") ?>vendor/FontAwesome/css/all.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/FontAwesome/js/all.js" rel="stylesheet">

<!-- Design CSS -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

<link href="<?= App::config("url") ?>vendor/css/design1.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design2.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design3.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design4.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design5.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design6.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design7.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design8.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design9.css" rel="stylesheet">
<link href="<?= App::config("url") ?>vendor/css/design10.css" rel="stylesheet">

<!-- custom CSS -->
<link href="<?= App::config("url") ?>vendor/css/style.css" rel="stylesheet">

<!-- Favicon -->
<link rel="shortcut icon" type="image/png" href="<?= App::config("url") ?>vendor/favicon.png"/>





