<!doctype html>
<html lang="hr">
<head>
    <title>Gymzone</title>
    <meta charset="utf-8">
    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="tinako.hr">
    <?php include "head_css.phtml"?>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <?php include "navbar.phtml"?>
    <?php include "sidebar.phtml";?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Nadzor</h1>

                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="<?= App::config("url") ?>Dashboard/Dashboard" class="linkanimation">Kontrolna ploča</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3><?=$activeUsersCount?></h3>
                                <p>Aktivnih korisnika</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-users"></i>
                            </div>
                            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3><?=$monthlyUserProportion?><sup style="font-size: 20px">%</sup></h3>
                                <p>Korisnika u odnosu na prošli mjesec</p>
                            </div>
                            <div class="icon">
                                <i class="fad fa-chart-bar"></i>
                            </div>
                            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3 style="color: #FFF"><?=$newMonthlyUsers->newMonthlyUsers?></h3>

                                <p style="color: #FFF">Novih korisnika ovaj mjesec</p>
                            </div>
                            <div class="icon">
                                <i class="fad fa-user-plus"></i>
                            </div>
                            <a href="#" class="small-box-footer"><span style="color: #FFF;">More info</span> <i class="fas fa-arrow-circle-right" style="color: #FFF;"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-danger">
                            <div class="inner">
                                <h3><?=$monthlyIncome->Users_Memberships_Price_Month?> KN</h3>
                                <p>Mjesečni prihodi</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-chart-line"></i>
                            </div>
                            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <section class="col-lg-8 connectedSortable">

                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Pregled korisnika</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                    <tr>
                                        <th>Šifra korisnika</th>
                                        <th>Ime i prezime</th>
                                        <th>Vrsta članarine</th>
                                        <th>Aktivan</th>
                                        <th>Datum početka</th>
                                        <th>Datum isteka</th>
                                        <th></th>
                                    </tr>
                                    </thead>

                                    <tfoot>
                                    <tr>
                                        <th>Šifra korisnika</th>
                                        <th>Ime i prezime</th>
                                        <th>Vrsta članarine</th>
                                        <th>Aktivan</th>
                                        <th>Datum početka</th>
                                        <th>Datum isteka</th>
                                        <th></th>
                                    </tr>
                                    </tfoot>

                                    <tbody>

                                    <?php
                                    $array=[];
                                    ?>

                                    <?php foreach ($userData as $data):?>
                                        <?php


                                        if (!in_array($Users_Memberships_Users_Id = $data->Users_Memberships_Users_Id, $array)):
                                            array_push($array, $Users_Memberships_Users_Id = $data->Users_Memberships_Users_Id);
                                            ?>
                                            <tr>
                                                <?php
                                                if (!empty($data->Users_Memberships_Start_Date)):
                                                    $timestamp = strtotime($data->Users_Memberships_Start_Date);
                                                    $realdate_Start = date("d.m.Y", $timestamp);

                                                    $timestamp = strtotime($data->Users_Memberships_End_Date);
                                                    $realdate_End = date("d.m.Y", $timestamp);
                                                else:
                                                    $realdate_Start = "";
                                                    $realdate_End = "";
                                                endif;
                                                ?>
                                                <td class="text-center"><?=$data->Users_Id?></td>
                                                <td class="text-center"><?=$data->Users_Name." ".$data->Users_Surname?>
                                                    <p>
                                                        <a href="<?= App::config("url") ?>User/Add_User_Arrival/<?=$data->Users_Id?>" class="btn linkanimation1"><span class="linkanimation1"><i
                                                                        class="fas fa-plus"></i> Potvrdi dolazak</span></a>
                                                    </p>
                                                </td>
                                                <td class="text-center"><?=$data->Users_Memberships_Membership_Name?></td>
                                                <td style="background-color: <?= $data->Users_Memberships_Membership_Active? "#29A745":"#DD3645" ?>; color: white; font-weight: bolder" class="text-center">
                                                    <?= $data->Users_Memberships_Membership_Active? "Da" : "Ne"?>
                                                </td>
                                                <td class="text-center"><?=$realdate_Start?></td>
                                                <td class="text-center"><?=$realdate_End?></td>
                                                <td class="text-center">
                                                    <p>
                                                        <a class="submitlink" href="<?=App::config("url")?>User/View_User/<?=$data->Users_Id?>"><i class="fad fa-user"></i></a>
                                                        <a class="submitlink" href="<?=App::config("url")?>User/Membership_Purchase/<?=$data->Users_Id?>"><i class="fas fa-plus"></i> </a>

                                                    </p>

                                                </td>
                                            </tr>
                                        <?
                                        else:
                                            continue;

                                        endif;
                                        ?>

                                    <? endforeach;?>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </section>
                    <section class="col-lg-4 connectedSortable">
                        <div class="card ">
                            <div class="card-header">
                                <h3 class="card-title">Statistika</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>

                                </div>
                            </div>
                            <div class="card-body">
                                <div class="chart">
                                    <canvas id="areaChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                                </div>
                            </div>
                        </div>
                        <div id="calendar"></div>
                        <div class="card bg-gradient-success">
                            <div class="card-body pt-0 text-center">
                                <h1 style="padding-top: 20px"><?=date('d.m.Y')?></h1>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </div>
    <?php include "footer.phtml";?>
</div>
<script>
    var areaChartCanvas = $('#areaChart').get(0).getContext('2d')

    var areaChartData = {
        labels  : ['Siječanj', 'Veljača', 'Ožujak', 'Travanj', 'Svibanj', 'Lipanj', 'Srpanj', 'Kolovoz', 'Rujan', 'Listopad', 'Studeni', 'Prosinac'],
        datasets: [
            {
                label               : 'Novi korisnici',
                backgroundColor     : 'rgba(116, 198, 135, 0.5)',
                borderColor         : 'rgba(116, 198, 135, 1)',
                pointRadius         : true,
                pointColor          : 'rgba(210, 214, 222, 1)',
                pointStrokeColor    : '#c1c7d1',
                pointHighlightFill  : '#fff',
                pointHighlightStroke: 'rgba(220,220,220,1)',
                data                : [65, 59, 80, 81, 56, 55, 40, 65, 59, 80, 81, 56, 55, 40]
            },
        ]
    }

    var areaChartOptions = {
        maintainAspectRatio : false,
        responsive : true,
        legend: {
            display: true
        },
        scales: {
            xAxes: [{
                gridLines : {
                    display : false,
                }
            }],
            yAxes: [{
                gridLines : {
                    display : true,
                }
            }]
        }
    }

    new Chart(areaChartCanvas, {
        type: 'line',
        data: areaChartData,
        options: areaChartOptions
    })
</script>

</body>
</html>