<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item ml-14">
            <a class="nav-link-dark" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="<?= App::config("url") ?>Dashboard/Dashboard" class="linkanimation ml-14">Kontrolna ploča</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="mailto:info@tinako.hr" class="linkanimation ml-14">Kontakt</a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">

        <!--
        <li class="nav-item dropdown">
            <a class="linkanimation ml-14" data-toggle="dropdown" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-search"></i>

            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" aria-labelledby="dropdownMenuButton2">
                <span class="dropdown-item dropdown-header">Pretraga korisnika</span>
                <div class="dropdown-divider"></div>
                <input type="text" placeholder="Pretraga korisnika" aria-label="Search">
            </div>
        </li>
 -->
        <!-- temp, za 1.1 verziju
        <li class="nav-item dropdown">
            <a class="linkanimation ml-14" data-toggle="dropdown" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">X</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" aria-labelledby="dropdownMenuButton2">
                <span class="dropdown-item dropdown-header">X Obavijesti</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-circle text-info mr-2"></i> Obavijest x
                    <span class="float-right text-muted text-sm">Datum</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-circle text-info mr-2"></i> Obavijest x
                    <span class="float-right text-muted text-sm">Datum</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-circle text-info mr-2"></i> Obavijest x
                    <span class="float-right text-muted text-sm">Datum</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="far fa-circle text-info-read mr-2"></i> Obavijest x
                    <span class="float-right text-muted text-sm">Datum</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
-->
        <li class="nav-item dropdown">
            <a class="linkanimation ml-14" data-toggle="dropdown" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" aria-labelledby="dropdownMenuButton1">
                <span class="dropdown-item dropdown-header">Moj račun</span>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item">
                    <i class="fas fa-user mr-2" style="width: 20px"></i> <?=$staffName?>
                </a>

                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-cogs mr-2" style="width: 20px"></i> Postavke
                </a>

                <div class="dropdown-divider"></div>
                <a href="<?= App::config("url") ?>Login/logout" class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2" style="width: 20px"></i> Odjava
                </a>

                <div class="dropdown-divider"></div>
            </div>
        </li>

        <li class="nav-item">
            <a class="linkanimation ml-14 mr-14" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
</nav>