<!-- Design JS -->
<script src="<?= App::config("url") ?>vendor/js/design1.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design2.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design3.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design4.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design5.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design6.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design7.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design8.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design9.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design10.js"></script>


<script src="<?= App::config("url") ?>vendor/js/design11.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design12.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design13.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design14.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design15.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design16.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design17.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design18.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design19.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design20.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design21.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design22.js"></script>

<script src="<?= App::config("url") ?>vendor/js/design23.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design24.js"></script>


<!-- Additional JS -->
<script src="<?= App::config("url") ?>vendor/js/scripts.js"></script>

<!-- Bootstrap -->
<script src="<?= App::config("url") ?>vendor/Bootstrap/bootstrap.js"></script>

<script>
    // Chart script
    var areaChartCanvas = $('#areaChart').get(0).getContext('2d')

    var areaChartData = {
        labels  : [<?php foreach ($monthsInYear as $my){echo $my." ,";}?>],
        datasets: [
            {
                label               : 'Novi korisnici',
                backgroundColor     : 'rgba(116, 198, 135, 0.5)',
                borderColor         : 'rgba(116, 198, 135, 1)',
                pointRadius         : true,
                pointColor          : 'rgba(210, 214, 222, 1)',
                pointStrokeColor    : '#c1c7d1',
                pointHighlightFill  : '#fff',
                pointHighlightStroke: 'rgba(220,220,220,1)',
                data                : [<?php foreach ($yearlyStats as $ys){echo  $ys->userData.", ";}?>]
            },
        ]
    }

    var areaChartOptions = {
        maintainAspectRatio : true,
        responsive : true,
        legend: {
            display: true
        },
        scales: {
            xAxes: [{
                gridLines : {
                    display : false,
                },
                scaleLabel: {
                    display: true,
                    labelString: 'Mjeseci'
                }
            }],
            yAxes: [{
                gridLines : {
                    display : true,
                }
            }]
        }
    }

    new Chart(areaChartCanvas, {
        type: 'line',
        data: areaChartData,
        options: areaChartOptions
    })

    // chart script end

    // profileData modal
    $('.profileData').on('click', function () {
        var id = $(this).attr('id');

        if (id) {
            id = id.split('_')[1];
            $.ajax({

                method: "POST",
                data: {data: id},
                url: 'http://localhost:8080/gym.com.hr_v2/User/viewUser/' + id,
                success: function (response) {
                    response = JSON.parse(response);

                    $("#profileData").modal('show');
                    $("#email").text(response["Users_Email"]);
                    $("#id").text(response["Users_Id"]);
                    $("#ime").text(response["Users_Name"]+" "+response["Users_Surname"]);
                    $("#telefon").text(response["Users_Phone"]);
                    $("#imeclanarine").text(response["Users_Memberships_Membership_Name"]);
                    $("#status").text(response["Users_Status"]);
                    $("#datumrodenja").text(formatDate (response["Users_Birthday"]));
                    $("#trajanjeclanarine").text(formatDate (response["Users_Memberships_Start_Date"])+"  -  "+formatDate (response["Users_Memberships_End_Date"]));
                    $("#brojdolazaka").text("Broj dolazaka ovaj tjedan: "+response["countrow"]);

                    $("#potvrdidolazak").html("<a href='<?= App::config("url") ?>User/addUserArrival/"+response["Users_Id"]+"'   ><span class='linkanimation_black' >Potvrdi dolazak</span></a>");

                }
            });
        }
    });

    //

    function formatDate (input) {
        var datePart = input.match(/\d+/g),
            year = datePart[0],
            month = datePart[1], day = datePart[2];
        return day+'.'+month+'.'+year+'.';
    }
    // profileData modal end

</script>