<!-- Design JS -->
<script src="<?= App::config("url") ?>vendor/js/design1.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design2.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design3.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design4.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design5.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design6.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design7.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design8.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design9.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design10.js"></script>


<script src="<?= App::config("url") ?>vendor/js/design11.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design12.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design13.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design14.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design15.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design16.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design17.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design18.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design19.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design20.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design21.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design22.js"></script>

<script src="<?= App::config("url") ?>vendor/js/design23.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design24.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design25.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design26.js"></script>


<!-- Additional JS -->
<script src="<?= App::config("url") ?>vendor/js/scripts.js"></script>

<!-- Bootstrap -->
<script src="<?= App::config("url") ?>vendor/Bootstrap/bootstrap.js"></script>

<script>
    // Chart script
    var areaChartCanvas = $('#areaChart').get(0).getContext('2d')

    var areaChartData = {
        labels  : [<?php foreach ($monthsInYear as $my){echo $my." ,";}?>],
        datasets: [
            {
                label               : 'Novi korisnici',
                backgroundColor     : 'rgba(116, 198, 135, 0.5)',
                borderColor         : 'rgba(116, 198, 135, 1)',
                pointRadius         : true,
                pointColor          : 'rgba(210, 214, 222, 1)',
                pointStrokeColor    : '#c1c7d1',
                pointHighlightFill  : '#fff',
                pointHighlightStroke: 'rgba(220,220,220,1)',
                data                : [<?php foreach ($yearlyStats as $ys){echo  $ys->userData.", ";}?>]
            },
        ]
    }

    var areaChartOptions = {
        maintainAspectRatio : true,
        responsive : true,
        legend: {
            display: true
        },
        scales: {
            xAxes: [{
                gridLines : {
                    display : false,
                },
                scaleLabel: {
                    display: true,
                    labelString: 'Mjeseci'
                }
            }],
            yAxes: [{
                gridLines : {
                    display : true,
                }
            }]
        }
    }

    new Chart(areaChartCanvas, {
        type: 'line',
        data: areaChartData,
        options: areaChartOptions
    })

    // chart script end

    // profileData modal
    $('.profileData').on('click', function () {
        var id = $(this).attr('id');

        if (id) {
            id = id.split('_')[1];
            $.ajax({

                method: "POST",
                data: {data: id},
                url: 'http://localhost:8080/gym.com.hr_v2/User/viewUser/' + id,
                success: function (response) {
                    response = JSON.parse(response);

                    $("#profileData").modal('show');
                    $("#email").text(response["Users_Email"]);
                    $("#id").text(response["Users_Id"]);
                    $("#usersName").text(response["Users_Name"]+" "+response["Users_Surname"]);
                    $("#usersPhone").text(response["Users_Phone"]);
                    $("#membershipName").text(response["Users_Memberships_Membership_Name"]);
                    $("#status").text(response["Users_Status"]);
                    $("#birthday").text(formatDate (response["Users_Birthday"]));
                    $("#membershipDuration").text(formatDate (response["Users_Memberships_Start_Date"])+"  -  "+formatDate (response["Users_Memberships_End_Date"]));
                    $("#numberOfArrivals").text("Broj dolazaka ovaj tjedan: "+response["countrow"]);

                    $("#confirmArrival").html("<a><span class='btn btn-block btn-outline-info' >Potvrda dolaska</span></a>");
                    globalVariable = response["Users_Id"];
                }
            });
        }
    });
    function formatDate (input) {
        var datePart = input.match(/\d+/g),
            year = datePart[0],
            month = datePart[1], day = datePart[2];
        return day+'.'+month+'.'+year+'.';
    }
    // profileData modal end


    // arrivalCounter
    $('.potvrdidolazak').on('click', function() {
        var id = globalVariable;
        $.ajax({

            method: "POST",
            data: {data: id},
            url: 'http://localhost:8080/gym.com.hr_v2/User/addUserArrival/' + id,
            success: function () { // do tu valja
                    $("#profileData").fadeOut(800, function (){
                        $(this).modal('hide');
                    });
                    $(this).fadeIn(400, function notification(){
                        successNotification('Uspješno potvrđen dolazak.')
                    });
            }

        });

    });
    // arrivalCounter end


    // widgets
    function successNotification(message){
        toastr.success(message)
    }
    function infoNotification(message){
        toastr.info(message)
    }
    function errorNotification(message){
        toastr.error(message)
    }
    function warningNotification(message){
        toastr.warning(message)
    }
    // widgets end


    // membershipData modal
    $('.membershipData').on('click', function () {

        var id = globalVariable;
        $("#profileData").fadeOut(400, function (){
            $(this).modal('hide');
        });

        if (id) {

            $.ajax({

                method: "POST",
                data: {data: id},
                url: 'http://localhost:8080/gym.com.hr_v2/User/allMemberships/',
                success: function (response) {

                    $('form').on('submit', function (e) {

                        e.preventDefault();

                        $.ajax({
                            type: 'post',
                            url: 'http://localhost:8080/gym.com.hr_v2/User/addNewUserMembership/'+id,
                            data: $('#formforma').serialize(),
                            success: function () {
                                $("#membershipData").fadeOut(800, function (){
                                    $(this).modal('hide');
                                });
                                $(this).fadeIn(400, function notification(){
                                    successNotification('Uspješno produžena članarina.')
                                });

                                /* Ovo je osvježavanje podataka da ne treba refresh*/
                                $.ajax({

                                    method: "POST",
                                    data: {data: id},
                                    url: 'http://localhost:8080/gym.com.hr_v2/User/viewUser/' + id,
                                    success: function (response) {
                                        response = JSON.parse(response);

                                        $("#"+id+"_membershipsStartDate").text(formatDate (response["Users_Memberships_Start_Date"]));
                                        $("#"+id+"_membershipsEndDate").text(formatDate (response["Users_Memberships_End_Date"]));
                                        $("#"+id+"_membershipsName").text(response["Users_Memberships_Membership_Name"]);
                                        $("#"+id+"_membershipsStatus").text("Da");
                                        document.getElementById(id+'_membershipsStatus').style.backgroundColor = "#74C687";

                                        globalVariable = response["Users_Id"];
                                    }
                                });
                            }
                        });

                    });

                    $("#membershipData").modal('show');

                    response = JSON.parse(response);

                    const membershipsData = document.getElementById('memberships');
                    const srcArray = response;

                    membershipsData.innerHTML = srcArray.reduce((options, {Memberships_Id,Memberships_Name}) =>
                            options+=`<option value="${Memberships_Name}" >${Memberships_Name}</option>`,
                            `<option value=""  selected="false" disabled="disabled">Odaberi članarinu</option>`);
                }
            });
        }
    });

    // membershipData modal end


    // Registration of new user
    $('.newUserRegistration').on('click', function () {
        $("#newUserRegistration").modal('show');
    });
</script>