<!-- Design JS -->
<script src="<?= App::config("url") ?>vendor/js/design1.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design2.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design3.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design4.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design5.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design6.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design7.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design8.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design9.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design10.js"></script>

<script src="<?= App::config("url") ?>vendor/js/design11.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design12.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design13.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design14.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design15.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design16.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design17.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design18.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design19.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design20.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design21.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design22.js"></script>

<script src="<?= App::config("url") ?>vendor/js/design23.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design24.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design25.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design26.js"></script>
<script src="<?= App::config("url") ?>vendor/js/design27.js"></script>

<!-- Additional JS -->
<script src="<?= App::config("url") ?>vendor/js/scripts.js"></script>
<script src="<?= App::config("url") ?>vendor/js/inputsanitizers.js"></script>

<!-- Bootstrap -->
<script src="<?= App::config("url") ?>vendor/Bootstrap/bootstrap.js"></script>

<script>
    // Variables start
    const urlAddress = 'http://localhost:8080/gym.com.hr_v2/';
    document.getElementById("dt1").style.display = "none";
    // Variables end


    // Chart script
    var areaChartCanvas = $('#areaChart').get(0).getContext('2d')

    var areaChartData = {
        labels: [<?php foreach ($monthsInYear as $my) {
            echo $my . " ,";
        }?>],
        datasets: [
            {
                label: 'Novi korisnici',
                backgroundColor: 'rgba(116, 198, 135, 0.5)',
                borderColor: 'rgba(116, 198, 135, 1)',
                pointRadius: true,
                pointColor: 'rgba(210, 214, 222, 1)',
                pointStrokeColor: '#c1c7d1',
                pointHighlightFill: '#fff',
                pointHighlightStroke: 'rgba(220,220,220,1)',
                data: [<?php foreach ($yearlyStats as $ys) {
                    echo $ys->userData . ", ";
                }?>]
            },
        ]
    }

    var areaChartOptions = {
        maintainAspectRatio: true,
        responsive: true,
        legend: {
            display: true
        },
        scales: {
            xAxes: [{
                gridLines: {
                    display: false,
                },
                scaleLabel: {
                    display: true,
                    labelString: 'Mjeseci'
                }
            }],
            yAxes: [{
                gridLines: {
                    display: true,
                }
            }]
        }
    }

    new Chart(areaChartCanvas, {
        type: 'line',
        data: areaChartData,
        options: areaChartOptions
    })

    // chart script end

    // soccer calendar start
    var Calendar = FullCalendar.Calendar;
    var calendarEl = document.getElementById('calendar');

    var calendar = new Calendar(calendarEl, {
        headerToolbar: {
            left  : 'prev,next today',
            center: 'title',
            right : 'dayGridMonth,timeGridWeek,timeGridDay'
        },
        themeSystem: 'bootstrap',

        /*
           parametri:
           {
           plava boja za nogomet: #16A2B8
                    title          : '',
                    start          : new Date(y, m, d, 12, 0),
                    end            : new Date(y, m, d, 14, 0),
                    backgroundColor: '#f56954', //red
                    borderColor    : '#f56954', //red
                    allDay         : false
                    url            : 'https://www.google.com/'
                },
        */

        events: [
            <?php foreach ($calendarData as $cd):?>
            {
                title          : '<?=$cd->Soccer_Contact_Name?>',
                start          : new Date(<?=$cd->SoccerYearStart?>,<?=($cd->SoccerMonthStart)-1?>, <?=$cd->SoccerDayStart?>, <?=$cd->SoccerHourStart?>, 0),
                end            : new Date(<?=$cd->SoccerYearEnd?>,<?=($cd->SoccerMonthEnd)-1?>, <?=$cd->SoccerDayEnd?>, <?=$cd->SoccerHourEnd?>, 0),
                backgroundColor: '#16A2B8',
                borderColor    : '#16A2B8',
                url            : urlAddress+'Check/test/<?=$cd->Soccer_Id?>',
                allDay         : false
            }
            <?php endforeach;?>,
        ],
        editable  : false,
        droppable : false,
    });
    calendar.render();

    // soccer calendar end
</script>