<aside class="main-sidebar sidebar-dark-primary elevation-4 bg-c-lite-green">
    <a href="<?= App::config("url") ?>Dashboard/Dashboard" class="brand-link">
        <span class="brand-text font-weight-light font_white">GYMZONE</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <p class="d-block linkanimation font_white"><?=$gymName?></p>
            </div>
        </div>

        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar nav-item" type="search" placeholder="Pretraga korisnika"
                       aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item ">
                    <a href="<?= App::config("url") ?>Dashboard/Dashboard" class="nav-link active"><i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Kontrolna ploča</p></a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            Teretane
                            <i class="fas fa-angle-left right"></i>
                            <span class="badge badge-info right"><?=$gymDataCount?></span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <?php foreach ($gymData as $gd)?>
                        <li class="nav-item">
                            <a href="pages/layout/top-nav.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p><?=$gd->Gym_Name?></p>
                            </a>
                        </li>

                    </ul>
                </li>

                <li class="nav-header">Korisnici</li>

                <li class="nav-item">
                    <a href="https://adminlte.io/docs/3.1/" class="nav-link">
                        <i class="nav-icon fas fa-user successColor"></i>
                        <p>Aktivni korisnici</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="https://adminlte.io/docs/3.1/" class="nav-link">
                        <i class="nav-icon fas fa-user dangerColor"></i>
                        <p>Inaktivni korisnici</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="https://adminlte.io/docs/3.1/" class="nav-link">
                        <i class="nav-icon fas fa-user neutralColor"></i>
                        <p>Svi korisnici</p>
                    </a>
                </li>

                <li class="nav-header">--</li>

                <li class="nav-item">
                    <a href="https://adminlte.io/docs/3.1/" class="nav-link">
                        <i class="nav-icon fas fa-plus"></i>
                        <p>Novi korisnik</p>
                    </a>
                </li>

                <li class="nav-header">Nadzor</li>

                <li class="nav-item">
                    <a href="https://adminlte.io/docs/3.1/" class="nav-link">
                        <i class="nav-icon fas fa-male successColor"></i>
                        <p>Zaposlenici</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="https://adminlte.io/docs/3.1/" class="nav-link">
                        <i class="nav-icon fas fa-file"></i>
                        <p>Članarine</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>
                            Statistika
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>
                            Financije
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-sticky-note"></i>
                        <p>
                            Napomene
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-coffee"></i>
                        <p>
                            Pića
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-history"></i>
                        <p>
                            Aktivnost
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>
                            Postavke
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>